<?php


namespace app\DefaultApp\Models;


use systeme\Model\Model;

class MotifElimination extends Model
{

    protected $table="motif_elimination";
    public $id,$motif;

    public function existe($motif){
        $con=self::connection();
        $req="select *from motif_elimination where motif=:motif";
        $stmt=$con->prepare($req);
        $stmt->execute(array(":motif"=>$motif));
        $data=$stmt->fetchAll(\PDO::FETCH_CLASS,__CLASS__);
        if(count($data)>0){
            return true;
        }
        return false;
    }

    public function add()
    {
        if($this->existe($this->motif)){
            return "Motif existe deja dans la base de donnée";
        }
        return parent::add(); // TODO: Change the autogenerated stub
    }
}
