<?php


namespace app\DefaultApp\Models;


use systeme\Model\Model;

class Prime extends Model
{
    public $id,$departement,$groupe,$reseau,$branche,$prime;

    private function supprimer($departement,$groupe,$reseau,$branche){
        $con=self::connection();
        $req="delete from prime where departement=:departement and groupe=:groupe
        and reseau=:reseau and branche=:branche";
        $stmt=$con->prepare($req);
        if($stmt->execute(array(
            ":departement"=>$departement,
            ":groupe"=>$groupe,
            ":reseau"=>$reseau,
            ":branche"=>$branche
        ))){
            return true;
        }
        return false;
    }

    public function add()
    {
        $this->supprimer($this->departement,$this->groupe,$this->reseau,$this->branche);
        return parent::add(); // TODO: Change the autogenerated stub
    }

    public function lister($departement,$groupe,$reseau,$branche){
        $con=self::connection();
        $req="select *from prime where departement=:departement and groupe=:groupe
        and reseau=:reseau and branche=:branche";
        $stmt=$con->prepare($req);
        $stmt->execute(array(
            ":departement"=>$departement,
            ":groupe"=>$groupe,
            ":reseau"=>$reseau,
            ":branche"=>$branche
        ));
        $data=$stmt->fetchAll(\PDO::FETCH_CLASS,__CLASS__);
        if(count($data)>0){
            return $data[0];
        }
        return null;
    }
}
